version: 2.1
orbs:
  node: "circleci/node@4.1.0"
executors:
  shared-docker:
    environment:
      IMAGE_NAME: joaoinez/haikus-pra-vida-backend
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  test-api:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./coverage
  build-image:
    executor: shared-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Save docker image as .tar
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  push-image:
    executor: shared-docker
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push image to DockerHub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              docker push $IMAGE_NAME:latest
            else
              docker tag $IMAGE_NAME:latest $IMAGE_NAME:development
              docker push $IMAGE_NAME:development
            fi
workflows:
  test-build-and-push:
    jobs:
      - test-api
      - build-image:
          requires:
            - test-api
          filters:
            branches:
              only:
                - master
                - development
      - push-image:
          context:
            - dockerhub-auth
          requires:
            - build-image
          filters:
            branches:
              only:
                - master
                - development
