version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    steps:
      - checkout
      - node/install-packages
        pkg-manager: yarn
      - run:
        name: Run tests
        command: yarn test
workflows:
  test-api:
    jobs:
      - test
